#!/bin/bash

cmd="$1"

case $cmd in

	"install")
		vagrant box add pre64-elife-rb1.9-chef-11 http://cdn.elifesciences.org/vm/pre64-elife-rb1.9-chef-11.box
		( \
		cd .. \
		git clone git@github.com:elifesciences/drupal-highwire.git \
		git clone git@github.com:elifesciences/drupal-site-jnl-elife.git \
		) \
		rm -rf Cheffile.lock cookbooks tmp
		;;

	"run")
		vagrant up
		;;

	"clean")
		rm -rf Cheffile.lock cookbooks tmp
		;;

	"provision")
		vagrant provision
		;;

esac
